### PR TITLE
restore ability to build with Visual Studio (in addition to cmake)

### PR DESCRIPTION
**Pull request by feeph**
As part of the migration to CMake and changing the directory layout the code can't be built using skse64.sln anymore. This patch restores the functionality and allows building with both VisualStudio and cmake using the same directory layout.

If the solution files are considered legacy and it's not desired to be able to use them to build Skyrim AE the targets 'Debug_VC142' and 'Release_VC142' should be removed. Leaving them hanging around in a broken state only adds confusion.

_Happy to make adjustments if you want me to.
You can treat this PR as a discussion starter._

### CODE REVIEW

**Comment by feeph** [comment]
Related: skse64.vcxproj defines targets 'Debug_Lib_VC142' and 'Release_Lib_VC142'. It's unclear what their purpose is.

Both targets should be considered for deletion or documented somewhere.

**Comment by ousnius** [comment]
Modern Visual Studio can deal with CMake pretty well without solution or project files, but nevertheless they're always neat to still have around.

**Comment by feeph** [comment]
I'm aware you can use cmake in Visual Studio 2019/2022 directly, but Readme.md states

> **Building:**
> Either use the pre-generated projects, or [...] cmake

and thus I thought it would be nice if using the projects actually works. Alternatively it could be decided there should be exactly one way to build SKSE for Skyrim AE and using the project files is no longer supported. In this case the Readme.md should be updated to indicate when to use which _(AE: cmake, VR/SE: projects)_ and all VC142-based targets should be removed entirely. (I'm fine either way, I just don't like this current, half-broken state.)

Please indicate which direction should be taken and I'll either finalize or revoke this PR.

**Comment by ousnius** [comment]
I'm not part of the SKSE team, I just stated my opinion which mostly aligns with yours.

**Comment by shadeMe** [comment]
As someone who maintains a SKSE64 plugin that is directly dependent on the SKSE plugin API (as opposed to the one offered by CommonLib), I would be happy to retain the ability to execute regular MsBuild builds using the VS projects, if only for the skse64_common project.

**Comment by feeph** [comment]
_Completed change has been submitted as **https://github.com/ianpatt/skse64/pull/8**._

**Pull request closed without merging**
