### PR TITLE
1.6.323 address fixes

### PR DESCRIPTION
**Pull request by expired6978**
Also some minor declaration changes

### CODE REVIEW

**Comment by feeph** [comment]
What is the purpose of 'sheets/'?
(There is no explanation in the commit or code why this change is made.)

**Comment by ianpatt** [comment]
I just got back from vacation and am met with a version update - sorry for delays. I would prefer splitting all of the build changes in to a separate patch for review; the address changes can go in no problem when updated for the new version.

**Comment by expired6978** [comment]
Was only supposed to be ca0c8a3 anyway. The build changes are just my local branch. The sheets are to move all the common project changes into separate files so changing one doesn't require changing every project individually. They are project relative as I have my own repository that is beside common and skse64 and links to them as dependencies in its own solution.

**Comment by ianpatt** [comment]
You checked in the build changes as well when merging this commit - if that was intentional please coordinate with https://github.com/ianpatt/skse64/pull/8 to support a standalone .sln, if not please revert.

**Pull request merged**
